import type { Page } from '@playwright/test';

const artistProfileLocators = (page: Page) => ({
	enterMarketplace: page.locator('a[href="/band"]'),
	registerAsTalent: page.locator('a[href="/register"]').filter({ hasText: 'Register as Talent' }),
	signInLink: page.locator('a[href="/login"]'),
	loginEmail: page.getByPlaceholder('you@example.com', { exact: true }),
	loginPassword: page.getByPlaceholder('Enter your password', { exact: true }),
	signInButton: page.getByRole('button', { name: 'Sign in', exact: true }),
	profileLink: page.locator('a[href="/band/artist/profile"]'),
	profileHeading: page.getByRole('heading', { name: 'Public Profile Management', exact: true }),
	legalName: page.locator('#name'),
	displayName: page.locator('#display_name'),
	countryCode: page.locator('select[aria-label="Country code"]'),
	mobileNumber: page.locator('#mobile_number'),
	yearsOfExperience: page.locator('#years_of_experience'),
	bio: page.locator('#bio'),
	bandType: page.locator('#band_type'),
	languageOption: (language: string) => page.getByRole('button', { name: language, exact: true }),
	genreOption: (genre: string) => page.getByRole('button', { name: genre, exact: true }),
	equipmentOption: (equipment: string) => page.getByRole('button').filter({
		has: page.getByText(equipment, { exact: true }),
	}),
	awardInput: page.getByPlaceholder('E.g. Best Rock Band - Bangalore Music Awards 2025', { exact: true }),
	addAwardButton: page.locator('button:has(svg.lucide-plus)'),
	awardItem: (award: string) => page.getByRole('tabpanel', { name: 'Edit Profile' })
		.getByText(award, { exact: true }),
	imageSection: (label: 'Avatar Photo' | 'Cover Banner') =>
		page.getByText(label, { exact: true }).locator('..'),
	imageUploadedToast: page.getByText('Image uploaded successfully!', { exact: true }),
	saveProfileButton: page.getByRole('button', { name: 'Save Profile Changes', exact: true }),
	profileUpdatedToast: page.getByText('Profile details updated successfully!', { exact: true }),
	galleryMediaTab: page.getByRole('tab', { name: 'Gallery / Media', exact: true }),
	publicPreviewTab: page.getByRole('tab', { name: 'Public Preview', exact: true }),
	publicPreviewPanel: page.locator('[role="tabpanel"][data-state="active"]'),
	activeTabPanel: page.locator('[role="tabpanel"][data-state="active"]'),
	galleryPhotoInput: page.locator('[role="tabpanel"][data-state="active"] input[type="file"][accept*="image"]'),
	demoVideoInput: page.locator('[role="tabpanel"][data-state="active"] input[type="file"][accept="video/*"]'),
	videoUploadLoading: page.locator('[role="tabpanel"][data-state="active"] [role="status"]')
		.getByText('Loading', { exact: true }),
	albumCategory: page.getByText('Select Album to upload into', { exact: true }).locator('..').locator('select'),
	youtubeLinkInput: page.getByPlaceholder('https://www.youtube.com/watch?v=...', { exact: true }),
	youtubeLinkAddButton: page.getByPlaceholder('https://www.youtube.com/watch?v=...')
		.locator('..').getByRole('button'),
	instagramUrl: page.getByPlaceholder('https://instagram.com/...', { exact: true }),
	twitterUrl: page.getByPlaceholder('https://twitter.com/...', { exact: true }),
	facebookUrl: page.getByPlaceholder('https://facebook.com/...', { exact: true }),
	websiteUrl: page.getByPlaceholder('https://www...', { exact: true }),
	saveMediaButton: page.getByRole('button', { name: 'Save Media Configuration', exact: true }),
	mediaSavedToast: page.getByText(/media configuration.*saved|saved.*media configuration/i),
	galleryImages: page.locator('[role="tabpanel"][data-state="active"] img[alt="Gallery item"]'),
	demoVideos: page.locator('[role="tabpanel"][data-state="active"] video'),
	pricingTab: page.getByRole('tab', { name: 'Pricing', exact: true }),
	currency: page.locator('[role="tabpanel"][data-state="active"] #currency'),
	performanceRate: page.getByText(/^Performance Rate \(/).locator('..').locator('input'),
	pricingTravelRadius: page.locator('[role="tabpanel"][data-state="active"] #travel_radius').first(),
	travelCharges: page.getByText(/^Travel Charges \/ Flat Fee \(/).locator('..').locator('input'),
	weekendSurcharge: page.locator('[role="tabpanel"][data-state="active"] #weekend_surcharge'),
	holidaySurcharge: page.locator('[role="tabpanel"][data-state="active"] #holiday_surcharge'),
	packageTitleInput: page.getByPlaceholder('E.g. Full Concert Setup', { exact: true }),
	packageDescriptionInput: page.getByPlaceholder(
		'E.g. Includes 3 hours performance, sound mixer, 4 mics, and lighting setup.',
		{ exact: true },
	),
	packagePriceInput: page.getByText(/^Flat Price \(/).locator('..').locator('input'),
	addPackageButton: page.getByRole('button', { name: 'Add Package Option', exact: true }),
	promoNameInput: page.getByPlaceholder('E.g. Early Bird Booking Discount', { exact: true }),
	promoDiscountInput: page.getByText('Discount (%)', { exact: true }).locator('..').locator('input'),
	promoTermsInput: page.getByPlaceholder(
		'E.g. 10% off for all shows booked at least 3 months in advance of the gig date.',
		{ exact: true },
	),
	addPromoButton: page.getByRole('button', { name: 'Add Promo Offer', exact: true }),
	savePricingButton: page.getByRole('button', { name: 'Save Pricing Configurations', exact: true }),
	pricingSavedToast: page.getByText(/pricing configurations saved successfully/i),
	pricingItem: (title: string) => page.getByRole('tabpanel', { name: 'Pricing' })
		.getByText(title, { exact: true }),
});

export = artistProfileLocators;